services:
  db:
    image: mariadb:11
    container_name: catty-db
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - catty-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  catty-app:
    image: ${IMAGE}
    container_name: ${APP_CONTAINER_NAME}
    restart: always
    ports:
      - "${HOST_APP_PORT}:${CONTEINER_APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - catty-network

networks:
  catty-network:
    driver: bridge

volumes:
  db_data:
