name: CD Pipeline

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get release commit SHA
        id: get_sha
        run: |
          RELEASE_TAG=${{ github.event.release.tag_name }}
          git clone --depth 1 --branch $RELEASE_TAG https://github.com/mzpdqk/catty-reminders-app.git /tmp/repo
          cd /tmp/repo
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Trigger Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -x
            cd /home/mzpdqk/devops/catty-reminders-app
            git fetch --all
            git reset --hard ${{ steps.get_sha.outputs.COMMIT_SHA }}
            /home/mzpdqk/devops/catty-reminders-app/venv/bin/pip install -q -r requirements.txt
            echo "DEPLOY_REF=${{ steps.get_sha.outputs.COMMIT_SHA }}" > .env
            sudo -n systemctl daemon-reload
            sudo -n systemctl restart app.service
            echo "Deployed ${{ steps.get_sha.outputs.COMMIT_SHA }}"
